const ADD_COMPANY = "ADD_COMPANY"; 
const ADD_DEPARTMENT = "ADD_DEPARTMENT";
// const ADD_TRANSACTION = "ADD_TRANSACTION";
// const UPDATE_BUDGET_PLAN = "UPDATE_BUDGET_PLAN"; 

export default {
    ADD_COMPANY, 
    ADD_DEPARTMENT    
}